/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'
import { Route as PlayMovieIdRouteImport } from './routes/play.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMovieIdRoute = PlayMovieIdRouteImport.update({
  id: '/play/$movieId',
  path: '/play/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/play/$movieId': typeof PlayMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/play/$movieId': typeof PlayMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/play/$movieId': typeof PlayMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/movie/$movieId'
    | '/play/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/movie/$movieId'
    | '/play/$movieId'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/movie/$movieId'
    | '/play/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  PlayMovieIdRoute: typeof PlayMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$movieId': {
      id: '/play/$movieId'
      path: '/play/$movieId'
      fullPath: '/play/$movieId'
      preLoaderRoute: typeof PlayMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
  PlayMovieIdRoute: PlayMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
